name: cnn_profiler_reg

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - tensorflow
  - tensorflow-hub
  - pillow
  - keras
  - line_profiler
  - pip
